In [1]:
import pandas as pd

In [42]:
def create_master_table(
    all_pokemons: pd.DataFrame, available_pokemons: pd.DataFrame, weakness_pokemons: pd.DataFrame
) -> pd.DataFrame:
    """Combines all data to create a master table.

        Args:
            all_pokemons: Preprocessed data for All Pokemons.
            available_pokemons: Preprocessed data for Available Pokemons.
            weakness_pokemons: Preprocessed data for Weakness Pokemons.
        Returns:
            Master table.

    """
#     available_pokemons_with_ID_and_types = all_pokemons.merge(available_pokemons, left_on="Name", right_on="Name_1")
    available_pokemons_with_ID_and_types = available_pokemons.merge(all_pokemons, left_on="Name_1", right_on="Name")
    with_weakness_1 = available_pokemons_with_ID_and_types.merge(weakness_pokemons, left_on='Type_1', right_on='Types')

#     with_companies = rated_shuttles.merge(
#         companies, left_on="company_id", right_on="id"
#     )

#     master_table = with_companies.drop(["shuttle_id", "company_id"], axis=1)
#     master_table = master_table.dropna()
    return with_weakness_1#master_table

In [43]:
master = create_master_table(all_pokemons, available_pokemons, weakness_pokemons)#, reviews)
master.head()

,Name_1,Level_1,Price_1,HP_1,Attack_1,Defense_1,Sp_Atk_1,Sp_Def_1,Speed_1,Legendary_1,...,Ground,Flying,Psychic,Bug,Rock,Ghost,Dragon,Dark,Steel,Fairy
0,Abra,4,346,32,22,17,115,61,99,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
1,Abra,26,614,80,38,26,197,103,170,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
2,Abra,33,775,102,48,33,247,131,214,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
3,Abra,45,937,129,56,39,298,158,257,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
4,Abra,46,963,133,58,40,306,162,264,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0

In [41]:
# Print Legendary with cost under 3500: 
master[(master['Legendary_1'] == True) & (master['Price_1']<3500)]
# Print cost over 3500
master[(master['Price_1'] > 3500)]

,Name_1,Level_1,Price_1,HP_1,Attack_1,Defense_1,Sp_Atk_1,Sp_Def_1,Speed_1,Legendary_1,...,Ground,Flying,Psychic,Bug,Rock,Ghost,Dragon,Dark,Steel,Fairy
9,Abra,94,3565,506,215,152,1126,594,972,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
16,Alakazam,76,3699,499,359,325,966,679,871,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
17,Alakazam,79,3904,526,379,343,1020,716,920,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
18,Alakazam,82,4087,550,397,360,1068,749,963,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
19,Alakazam,90,4615,621,447,407,1207,845,1088,False,...,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408,Machamp,97,6951,1330,1764,1087,877,1144,749,False,...,1.0,0.6,0.6,0.6,6.0,0.6,1.0,6.0,6.0,0.6
1409,Machamp,99,7350,1406,1865,1149,928,1210,792,False,...,1.0,0.6,0.6,0.6,6.0,0.6,1.0,6.0,6.0,0.6
1418,Machoke,89,3567,867,838,584,403,511,364,False,...,1.0,0.6,0.6,0.6,6.0,0.6,1.0,6.0,6.0,0.6
1419,Machoke,97,4276,1039,1005,698,484,614,436,False,...,1.0,0.6,0.6,0.6,6.0,0.6,1.0,6.0,6.0,0.6
1449,Primeape,98,5763,863,1329,744,744,880,1203,False,...,1.0,0.6,0.6,0.6,6.0,0.6,1.0,6.0,6.0,0.6

In [20]:
all_pokemons = catalog.load("all_pokemons")
available_pokemons = catalog.load("available_pokemons")
weakness_pokemons = catalog.load("weakness_pokemons")
battle_results = catalog.load("battle_results")
#submission = catalog.load("submission")

print(all_pokemons.head())
print(available_pokemons.head())
print(weakness_pokemons.head())
print(battle_results.head())
#print(submission.head())

2020-05-20 10:26:11,237 - kedro.io.data_catalog - INFO - Loading data from `all_pokemons` (CSVDataSet)...
2020-05-20 10:26:11,244 - kedro.io.data_catalog - INFO - Loading data from `available_pokemons` (CSVDataSet)...
2020-05-20 10:26:11,255 - kedro.io.data_catalog - INFO - Loading data from `weakness_pokemons` (CSVDataSet)...
2020-05-20 10:26:11,264 - kedro.io.data_catalog - INFO - Loading data from `battle_results` (CSVDataSet)...
   ID        Name Type_1  Type_2
0   1   Bulbasaur  Grass  Poison
1   2     Ivysaur  Grass  Poison
2   3    Venusaur  Grass  Poison
3   4  Charmander   Fire     NaN
4   5  Charmeleon   Fire     NaN
  Name_1  Level_1  Price_1  HP_1  Attack_1  Defense_1  Sp_Atk_1  Sp_Def_1  \
0   Abra        4      346    32        22         17       115        61
1   Abra       26      614    80        38         26       197       103
2   Abra       33      775   102        48         33       247       131
3   Abra       45      937   129        56         39       298       158
4   Abra       46      963   133        58         40       306       162

   Speed_1  Legendary_1  SelectedPokemonID
0       99        False                  1
1      170        False                  2
2      214        False                  3
3      257        False                  4
4      264        False                  5
      Types  Normal  Fire  Water  Electric  Grass  Ice  Fighting  Poison  \
0    Normal     1.0   1.0    1.0       1.0    1.0  1.0       1.0     1.0
1      Fire     1.0   0.6    0.6       1.0   50.0  6.0       1.0     1.0
2     Water     1.0  20.0    0.6       1.0    0.6  1.0       1.0     1.0
3  Electric     1.0   1.0    6.0       0.6    0.6  1.0       1.0     1.0
4     Grass     1.0   0.6    6.0       1.0    0.6  1.0       1.0     0.6

   Ground  Flying  Psychic  Bug  Rock  Ghost  Dragon  Dark  Steel  Fairy
0     1.0     1.0      1.0  1.0   0.6    0.6     1.0   1.0    0.6    1.0
1     1.0     1.0      1.0  6.0   0.6    1.0     0.6   1.0    6.0    1.0
2     6.0     1.0      1.0  1.0   6.0    1.0     0.6   1.0    1.0    1.0
3     0.6     6.0      1.0  1.0   1.0    1.0     0.6   1.0    1.0    1.0
4     6.0     0.6      1.0  0.6   6.0    1.0     0.6   1.0    0.6    1.0
    Name_1  Level_1  Price_1  HP_1  Attack_1  Defense_1  Sp_Atk_1  Sp_Def_1  \
0  Metapod       30      441   150        36        103        47        47
1   Pinsir       36     1227   196       304        237       129       164
2  Metapod       15      297    92        26         73        33        33
3   Pinsir       40     1401   228       346        270       146       187
4   Pinsir       12      634    91       157        124        70        86

   Speed_1  Legendary_1  ... Price_2  HP_2  Attack_2  Defense_2  Sp_Atk_2  \
0       58        False  ...    1589   262       393        306       164
1      197        False  ...    1583   547       127        365       172
2       40        False  ...    4913   821      1208        947       504
3      224        False  ...     588   202        47        138        63
4      106        False  ...     381   126        32         90        41

   Sp_Def_2  Speed_2  Legendary_2  WeatherAndTime  BattleResult
0       211      253        False           Windy          -262
1       172      200        False         Unknown          -424
2       652      781        False           Windy          -821
3        63       75        False         Unknown           214
4        41       51        False           Windy            41

[5 rows x 22 columns]

In [45]:
battle_results.keys()

Index(['Name_1', 'Level_1', 'Price_1', 'HP_1', 'Attack_1', 'Defense_1',
       'Sp_Atk_1', 'Sp_Def_1', 'Speed_1', 'Legendary_1', 'Name_2', 'Level_2',
       'Price_2', 'HP_2', 'Attack_2', 'Defense_2', 'Sp_Atk_2', 'Sp_Def_2',
       'Speed_2', 'Legendary_2', 'WeatherAndTime', 'BattleResult'],
      dtype='object')